services:
  - type: web
    name: noteflow-backend
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      flask db upgrade
    startCommand: "gunicorn app:app"
    # healthCheckPath: /health
    # healthCheckIntervalSeconds: 10
    env: python
    pythonVersion: "3.11.9"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: noteflow-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OAUTH_REDIRECT_URI
        value: https://noteflow-backend.onrender.com/auth/google/callback
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/static/uploads

databases:
  - name: noteflow-db
    plan: free
    databaseName: noteflow
    user: noteflow